#! /usr/bin/env python3

import sys

if len(sys.argv) < 2:
    print("Usage: <{}> <Number>".format(sys.argv[0]))
    sys.exit(-1)
    
print("{} -> {}".format(sys.argv[1], int(sys.argv[1], 0)))

    
