#! /usr/bin/env python3

import argparse
import os

umask_idx = 0
event_idx = 1
skl_events = {
    "baclears_any": ["0x01", "0xe6"],
    "branch_instructions_retired": ["0x00", "0xc4"],
    "br_inst_retired_cond": ["0x01", "0xc4"],
    "br_inst_retired_far_branch": ["0x40", "0xc4"],
    "br_inst_retired_near_call": ["0x02", "0xc4"],
    "br_inst_retired_near_return": ["0x08", "0xc4"],
    "br_inst_retired_near_taken": ["0x20", "0xc4"],
    "br_inst_retired_not_taken": ["0x10", "0xc4"],
    "br_misp_retired_cond": ["0x01", "0xc5"],
    "br_misp_retired_near_call": ["0x02", "0xc5"],
    "br_misp_retired_near_taken": ["0x20", "0xc5"],
    "core_snoop_response_rsp_ifwdfe": ["0x20", "0xef"],
    "core_snoop_response_rsp_ifwdm": ["0x10", "0xef"],
    "core_snoop_response_rsp_ihitfse": ["0x02", "0xef"],
    "core_snoop_response_rsp_ihiti": ["0x01", "0xef"],
    "core_snoop_response_rsp_sfwdfe": ["0x40", "0xef"],
    "core_snoop_response_rsp_sfwdm": ["0x08", "0xef"],
    "core_snoop_response_rsp_shitfse": ["0x04", "0xef"],
    "cpu_clk_thread_unhalted_one_thread_active": ["0x02", "0x3c"],
    "cpu_clk_unhalted": ["0x00", "0x3c"],
    "dsb2mite_switches_penalty_cycles": ["0x02", "0xab"],
    "dtlb_load_misses_miss_causes_a_walk": ["0x01", "0x08"],
    "dtlb_load_misses_stlb_hit": ["0x20", "0x08"],
    "dtlb_load_misses_walk_completed": ["0x0e", "0x08"],
    "dtlb_load_misses_walk_completed_1g": ["0x08", "0x08"],
    "dtlb_load_misses_walk_completed_2m_4m": ["0x04", "0x08"],
    "dtlb_load_misses_walk_completed_4k": ["0x02", "0x08"],
    "dtlb_load_misses_walk_pending": ["0x10", "0x08"],
    "dtlb_store_misses_miss_causes_a_walk": ["0x01", "0x49"],
    "dtlb_store_misses_stlb_hit": ["0x20", "0x49"],
    "dtlb_store_misses_walk_completed": ["0x0e", "0x49"],
    "dtlb_store_misses_walk_completed_1g": ["0x08", "0x49"],
    "dtlb_store_misses_walk_completed_2m_4m": ["0x04", "0x49"],
    "dtlb_store_misses_walk_completed_4k": ["0x02", "0x49"],
    "dtlb_store_misses_walk_pending": ["0x10", "0x49"],
    "ept_walk_pending": ["0x10", "0x4f"],
    "exe_activity_1_ports_util": ["0x02", "0xa6"],
    "exe_activity_2_ports_util": ["0x04", "0xa6"],
    "exe_activity_3_ports_util": ["0x08", "0xa6"],
    "exe_activity_4_ports_util": ["0x10", "0xa6"],
    "exe_activity_bound_on_stores": ["0x40", "0xa6"],
    "exe_activity_exe_bound_0_ports": ["0x01", "0xa6"],
    "fp_arith_128b_packed_double": ["0x04", "0xc7"],
    "fp_arith_128b_packed_double_128b_packed_single": ["0x0c", "0xc7"],
    "fp_arith_128b_packed_double_128b_packed_single_256b_packed_double":
    ["0x1c", "0xc7"],
    "fp_arith_128b_packed_double_128b_packed_single_256b_packed_double_256b_packed_single":
    ["0x3c", "0xc7"],
    "fp_arith_128b_packed_double_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_double":
    ["0x7c", "0xc7"],
    "fp_arith_128b_packed_double_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xfc", "0xc7"],
    "fp_arith_128b_packed_double_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_single":
    ["0xbc", "0xc7"],
    "fp_arith_128b_packed_double_128b_packed_single_256b_packed_double_512b_packed_double":
    ["0x5c", "0xc7"],
    "fp_arith_128b_packed_double_128b_packed_single_256b_packed_double_512b_packed_double_512b_packed_single":
    ["0xdc", "0xc7"],
    "fp_arith_128b_packed_double_128b_packed_single_256b_packed_double_512b_packed_single":
    ["0x9c", "0xc7"],
    "fp_arith_128b_packed_double_128b_packed_single_256b_packed_single":
    ["0x2c", "0xc7"],
    "fp_arith_128b_packed_double_128b_packed_single_256b_packed_single_512b_packed_double":
    ["0x6c", "0xc7"],
    "fp_arith_128b_packed_double_128b_packed_single_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xec", "0xc7"],
    "fp_arith_128b_packed_double_128b_packed_single_256b_packed_single_512b_packed_single":
    ["0xac", "0xc7"],
    "fp_arith_128b_packed_double_128b_packed_single_512b_packed_double": [
        "0x4c", "0xc7"
    ],
    "fp_arith_128b_packed_double_128b_packed_single_512b_packed_double_512b_packed_single":
    ["0xcc", "0xc7"],
    "fp_arith_128b_packed_double_128b_packed_single_512b_packed_single": [
        "0x8c", "0xc7"
    ],
    "fp_arith_128b_packed_double_256b_packed_double": ["0x14", "0xc7"],
    "fp_arith_128b_packed_double_256b_packed_double_256b_packed_single": [
        "0x34", "0xc7"
    ],
    "fp_arith_128b_packed_double_256b_packed_double_256b_packed_single_512b_packed_double":
    ["0x74", "0xc7"],
    "fp_arith_128b_packed_double_256b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xf4", "0xc7"],
    "fp_arith_128b_packed_double_256b_packed_double_256b_packed_single_512b_packed_single":
    ["0xb4", "0xc7"],
    "fp_arith_128b_packed_double_256b_packed_double_512b_packed_double": [
        "0x54", "0xc7"
    ],
    "fp_arith_128b_packed_double_256b_packed_double_512b_packed_double_512b_packed_single":
    ["0xd4", "0xc7"],
    "fp_arith_128b_packed_double_256b_packed_double_512b_packed_single": [
        "0x94", "0xc7"
    ],
    "fp_arith_128b_packed_double_256b_packed_single": ["0x24", "0xc7"],
    "fp_arith_128b_packed_double_256b_packed_single_512b_packed_double": [
        "0x64", "0xc7"
    ],
    "fp_arith_128b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xe4", "0xc7"],
    "fp_arith_128b_packed_double_256b_packed_single_512b_packed_single": [
        "0xa4", "0xc7"
    ],
    "fp_arith_128b_packed_double_512b_packed_double": ["0x44", "0xc7"],
    "fp_arith_128b_packed_double_512b_packed_double_512b_packed_single": [
        "0xc4", "0xc7"
    ],
    "fp_arith_128b_packed_double_512b_packed_single": ["0x84", "0xc7"],
    "fp_arith_128b_packed_single": ["0x08", "0xc7"],
    "fp_arith_128b_packed_single_256b_packed_double": ["0x18", "0xc7"],
    "fp_arith_128b_packed_single_256b_packed_double_256b_packed_single": [
        "0x38", "0xc7"
    ],
    "fp_arith_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_double":
    ["0x78", "0xc7"],
    "fp_arith_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xf8", "0xc7"],
    "fp_arith_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_single":
    ["0xb8", "0xc7"],
    "fp_arith_128b_packed_single_256b_packed_double_512b_packed_double": [
        "0x58", "0xc7"
    ],
    "fp_arith_128b_packed_single_256b_packed_double_512b_packed_double_512b_packed_single":
    ["0xd8", "0xc7"],
    "fp_arith_128b_packed_single_256b_packed_double_512b_packed_single": [
        "0x98", "0xc7"
    ],
    "fp_arith_128b_packed_single_256b_packed_single": ["0x28", "0xc7"],
    "fp_arith_128b_packed_single_256b_packed_single_512b_packed_double": [
        "0x68", "0xc7"
    ],
    "fp_arith_128b_packed_single_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xe8", "0xc7"],
    "fp_arith_128b_packed_single_256b_packed_single_512b_packed_single": [
        "0xa8", "0xc7"
    ],
    "fp_arith_128b_packed_single_512b_packed_double": ["0x48", "0xc7"],
    "fp_arith_128b_packed_single_512b_packed_double_512b_packed_single": [
        "0xc8", "0xc7"
    ],
    "fp_arith_128b_packed_single_512b_packed_single": ["0x88", "0xc7"],
    "fp_arith_256b_packed_double": ["0x10", "0xc7"],
    "fp_arith_256b_packed_double_256b_packed_single": ["0x30", "0xc7"],
    "fp_arith_256b_packed_double_256b_packed_single_512b_packed_double": [
        "0x70", "0xc7"
    ],
    "fp_arith_256b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xf0", "0xc7"],
    "fp_arith_256b_packed_double_256b_packed_single_512b_packed_single": [
        "0xb0", "0xc7"
    ],
    "fp_arith_256b_packed_double_512b_packed_double": ["0x50", "0xc7"],
    "fp_arith_256b_packed_double_512b_packed_double_512b_packed_single": [
        "0xd0", "0xc7"
    ],
    "fp_arith_256b_packed_double_512b_packed_single": ["0x90", "0xc7"],
    "fp_arith_256b_packed_single": ["0x20", "0xc7"],
    "fp_arith_256b_packed_single_512b_packed_double": ["0x60", "0xc7"],
    "fp_arith_256b_packed_single_512b_packed_double_512b_packed_single": [
        "0xe0", "0xc7"
    ],
    "fp_arith_256b_packed_single_512b_packed_single": ["0xa0", "0xc7"],
    "fp_arith_512b_packed_double": ["0x40", "0xc7"],
    "fp_arith_512b_packed_double_512b_packed_single": ["0xc0", "0xc7"],
    "fp_arith_512b_packed_single": ["0x80", "0xc7"],
    "fp_arith_scalar_double": ["0x01", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double": ["0x05", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_128b_packed_single": [
        "0x0d", "0xc7"
    ],
    "fp_arith_scalar_double_128b_packed_double_128b_packed_single_256b_packed_double":
    ["0x1d", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_128b_packed_single_256b_packed_double_256b_packed_single":
    ["0x3d", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_double":
    ["0x7d", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xfd", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_single":
    ["0xbd", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_128b_packed_single_256b_packed_double_512b_packed_double":
    ["0x5d", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_128b_packed_single_256b_packed_double_512b_packed_double_512b_packed_single":
    ["0xdd", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_128b_packed_single_256b_packed_double_512b_packed_single":
    ["0x9d", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_128b_packed_single_256b_packed_single":
    ["0x2d", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_128b_packed_single_256b_packed_single_512b_packed_double":
    ["0x6d", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_128b_packed_single_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xed", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_128b_packed_single_256b_packed_single_512b_packed_single":
    ["0xad", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_128b_packed_single_512b_packed_double":
    ["0x4d", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_128b_packed_single_512b_packed_double_512b_packed_single":
    ["0xcd", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_128b_packed_single_512b_packed_single":
    ["0x8d", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_256b_packed_double": [
        "0x15", "0xc7"
    ],
    "fp_arith_scalar_double_128b_packed_double_256b_packed_double_256b_packed_single":
    ["0x35", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_256b_packed_double_256b_packed_single_512b_packed_double":
    ["0x75", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_256b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xf5", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_256b_packed_double_256b_packed_single_512b_packed_single":
    ["0xb5", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_256b_packed_double_512b_packed_double":
    ["0x55", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_256b_packed_double_512b_packed_double_512b_packed_single":
    ["0xd5", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_256b_packed_double_512b_packed_single":
    ["0x95", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_256b_packed_single": [
        "0x25", "0xc7"
    ],
    "fp_arith_scalar_double_128b_packed_double_256b_packed_single_512b_packed_double":
    ["0x65", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xe5", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_256b_packed_single_512b_packed_single":
    ["0xa5", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_512b_packed_double": [
        "0x45", "0xc7"
    ],
    "fp_arith_scalar_double_128b_packed_double_512b_packed_double_512b_packed_single":
    ["0xc5", "0xc7"],
    "fp_arith_scalar_double_128b_packed_double_512b_packed_single": [
        "0x85", "0xc7"
    ],
    "fp_arith_scalar_double_128b_packed_single": ["0x09", "0xc7"],
    "fp_arith_scalar_double_128b_packed_single_256b_packed_double": [
        "0x19", "0xc7"
    ],
    "fp_arith_scalar_double_128b_packed_single_256b_packed_double_256b_packed_single":
    ["0x39", "0xc7"],
    "fp_arith_scalar_double_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_double":
    ["0x79", "0xc7"],
    "fp_arith_scalar_double_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xf9", "0xc7"],
    "fp_arith_scalar_double_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_single":
    ["0xb9", "0xc7"],
    "fp_arith_scalar_double_128b_packed_single_256b_packed_double_512b_packed_double":
    ["0x59", "0xc7"],
    "fp_arith_scalar_double_128b_packed_single_256b_packed_double_512b_packed_double_512b_packed_single":
    ["0xd9", "0xc7"],
    "fp_arith_scalar_double_128b_packed_single_256b_packed_double_512b_packed_single":
    ["0x99", "0xc7"],
    "fp_arith_scalar_double_128b_packed_single_256b_packed_single": [
        "0x29", "0xc7"
    ],
    "fp_arith_scalar_double_128b_packed_single_256b_packed_single_512b_packed_double":
    ["0x69", "0xc7"],
    "fp_arith_scalar_double_128b_packed_single_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xe9", "0xc7"],
    "fp_arith_scalar_double_128b_packed_single_256b_packed_single_512b_packed_single":
    ["0xa9", "0xc7"],
    "fp_arith_scalar_double_128b_packed_single_512b_packed_double": [
        "0x49", "0xc7"
    ],
    "fp_arith_scalar_double_128b_packed_single_512b_packed_double_512b_packed_single":
    ["0xc9", "0xc7"],
    "fp_arith_scalar_double_128b_packed_single_512b_packed_single": [
        "0x89", "0xc7"
    ],
    "fp_arith_scalar_double_256b_packed_double": ["0x11", "0xc7"],
    "fp_arith_scalar_double_256b_packed_double_256b_packed_single": [
        "0x31", "0xc7"
    ],
    "fp_arith_scalar_double_256b_packed_double_256b_packed_single_512b_packed_double":
    ["0x71", "0xc7"],
    "fp_arith_scalar_double_256b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xf1", "0xc7"],
    "fp_arith_scalar_double_256b_packed_double_256b_packed_single_512b_packed_single":
    ["0xb1", "0xc7"],
    "fp_arith_scalar_double_256b_packed_double_512b_packed_double": [
        "0x51", "0xc7"
    ],
    "fp_arith_scalar_double_256b_packed_double_512b_packed_double_512b_packed_single":
    ["0xd1", "0xc7"],
    "fp_arith_scalar_double_256b_packed_double_512b_packed_single": [
        "0x91", "0xc7"
    ],
    "fp_arith_scalar_double_256b_packed_single": ["0x21", "0xc7"],
    "fp_arith_scalar_double_256b_packed_single_512b_packed_double": [
        "0x61", "0xc7"
    ],
    "fp_arith_scalar_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xe1", "0xc7"],
    "fp_arith_scalar_double_256b_packed_single_512b_packed_single": [
        "0xa1", "0xc7"
    ],
    "fp_arith_scalar_double_512b_packed_double": ["0x41", "0xc7"],
    "fp_arith_scalar_double_512b_packed_double_512b_packed_single": [
        "0xc1", "0xc7"
    ],
    "fp_arith_scalar_double_512b_packed_single": ["0x81", "0xc7"],
    "fp_arith_scalar_double_scalar_single": ["0x03", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double": [
        "0x07", "0xc7"
    ],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_128b_packed_single":
    ["0x0f", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_128b_packed_single_256b_packed_double":
    ["0x1f", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_128b_packed_single_256b_packed_double_256b_packed_single":
    ["0x3f", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_double":
    ["0x7f", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xff", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_single":
    ["0xbf", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_128b_packed_single_256b_packed_double_512b_packed_double":
    ["0x5f", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_128b_packed_single_256b_packed_double_512b_packed_double_512b_packed_single":
    ["0xdf", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_128b_packed_single_256b_packed_double_512b_packed_single":
    ["0x9f", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_128b_packed_single_256b_packed_single":
    ["0x2f", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_128b_packed_single_256b_packed_single_512b_packed_double":
    ["0x6f", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_128b_packed_single_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xef", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_128b_packed_single_256b_packed_single_512b_packed_single":
    ["0xaf", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_128b_packed_single_512b_packed_double":
    ["0x4f", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_128b_packed_single_512b_packed_double_512b_packed_single":
    ["0xcf", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_128b_packed_single_512b_packed_single":
    ["0x8f", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_256b_packed_double":
    ["0x17", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_256b_packed_double_256b_packed_single":
    ["0x37", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_256b_packed_double_256b_packed_single_512b_packed_double":
    ["0x77", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_256b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xf7", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_256b_packed_double_256b_packed_single_512b_packed_single":
    ["0xb7", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_256b_packed_double_512b_packed_double":
    ["0x57", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_256b_packed_double_512b_packed_double_512b_packed_single":
    ["0xd7", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_256b_packed_double_512b_packed_single":
    ["0x97", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_256b_packed_single":
    ["0x27", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_256b_packed_single_512b_packed_double":
    ["0x67", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xe7", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_256b_packed_single_512b_packed_single":
    ["0xa7", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_512b_packed_double":
    ["0x47", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_512b_packed_double_512b_packed_single":
    ["0xc7", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_double_512b_packed_single":
    ["0x87", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_single": [
        "0x0b", "0xc7"
    ],
    "fp_arith_scalar_double_scalar_single_128b_packed_single_256b_packed_double":
    ["0x1b", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_single_256b_packed_double_256b_packed_single":
    ["0x3b", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_double":
    ["0x7b", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xfb", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_single":
    ["0xbb", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_single_256b_packed_double_512b_packed_double":
    ["0x5b", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_single_256b_packed_double_512b_packed_double_512b_packed_single":
    ["0xdb", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_single_256b_packed_double_512b_packed_single":
    ["0x9b", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_single_256b_packed_single":
    ["0x2b", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_single_256b_packed_single_512b_packed_double":
    ["0x6b", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_single_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xeb", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_single_256b_packed_single_512b_packed_single":
    ["0xab", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_single_512b_packed_double":
    ["0x4b", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_single_512b_packed_double_512b_packed_single":
    ["0xcb", "0xc7"],
    "fp_arith_scalar_double_scalar_single_128b_packed_single_512b_packed_single":
    ["0x8b", "0xc7"],
    "fp_arith_scalar_double_scalar_single_256b_packed_double": [
        "0x13", "0xc7"
    ],
    "fp_arith_scalar_double_scalar_single_256b_packed_double_256b_packed_single":
    ["0x33", "0xc7"],
    "fp_arith_scalar_double_scalar_single_256b_packed_double_256b_packed_single_512b_packed_double":
    ["0x73", "0xc7"],
    "fp_arith_scalar_double_scalar_single_256b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xf3", "0xc7"],
    "fp_arith_scalar_double_scalar_single_256b_packed_double_256b_packed_single_512b_packed_single":
    ["0xb3", "0xc7"],
    "fp_arith_scalar_double_scalar_single_256b_packed_double_512b_packed_double":
    ["0x53", "0xc7"],
    "fp_arith_scalar_double_scalar_single_256b_packed_double_512b_packed_double_512b_packed_single":
    ["0xd3", "0xc7"],
    "fp_arith_scalar_double_scalar_single_256b_packed_double_512b_packed_single":
    ["0x93", "0xc7"],
    "fp_arith_scalar_double_scalar_single_256b_packed_single": [
        "0x23", "0xc7"
    ],
    "fp_arith_scalar_double_scalar_single_256b_packed_single_512b_packed_double":
    ["0x63", "0xc7"],
    "fp_arith_scalar_double_scalar_single_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xe3", "0xc7"],
    "fp_arith_scalar_double_scalar_single_256b_packed_single_512b_packed_single":
    ["0xa3", "0xc7"],
    "fp_arith_scalar_double_scalar_single_512b_packed_double": [
        "0x43", "0xc7"
    ],
    "fp_arith_scalar_double_scalar_single_512b_packed_double_512b_packed_single":
    ["0xc3", "0xc7"],
    "fp_arith_scalar_double_scalar_single_512b_packed_single": [
        "0x83", "0xc7"
    ],
    "fp_arith_scalar_single": ["0x02", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double": ["0x06", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_128b_packed_single": [
        "0x0e", "0xc7"
    ],
    "fp_arith_scalar_single_128b_packed_double_128b_packed_single_256b_packed_double":
    ["0x1e", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_128b_packed_single_256b_packed_double_256b_packed_single":
    ["0x3e", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_double":
    ["0x7e", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xfe", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_single":
    ["0xbe", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_128b_packed_single_256b_packed_double_512b_packed_double":
    ["0x5e", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_128b_packed_single_256b_packed_double_512b_packed_double_512b_packed_single":
    ["0xde", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_128b_packed_single_256b_packed_double_512b_packed_single":
    ["0x9e", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_128b_packed_single_256b_packed_single":
    ["0x2e", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_128b_packed_single_256b_packed_single_512b_packed_double":
    ["0x6e", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_128b_packed_single_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xee", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_128b_packed_single_256b_packed_single_512b_packed_single":
    ["0xae", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_128b_packed_single_512b_packed_double":
    ["0x4e", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_128b_packed_single_512b_packed_double_512b_packed_single":
    ["0xce", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_128b_packed_single_512b_packed_single":
    ["0x8e", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_256b_packed_double": [
        "0x16", "0xc7"
    ],
    "fp_arith_scalar_single_128b_packed_double_256b_packed_double_256b_packed_single":
    ["0x36", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_256b_packed_double_256b_packed_single_512b_packed_double":
    ["0x76", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_256b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xf6", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_256b_packed_double_256b_packed_single_512b_packed_single":
    ["0xb6", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_256b_packed_double_512b_packed_double":
    ["0x56", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_256b_packed_double_512b_packed_double_512b_packed_single":
    ["0xd6", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_256b_packed_double_512b_packed_single":
    ["0x96", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_256b_packed_single": [
        "0x26", "0xc7"
    ],
    "fp_arith_scalar_single_128b_packed_double_256b_packed_single_512b_packed_double":
    ["0x66", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xe6", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_256b_packed_single_512b_packed_single":
    ["0xa6", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_512b_packed_double": [
        "0x46", "0xc7"
    ],
    "fp_arith_scalar_single_128b_packed_double_512b_packed_double_512b_packed_single":
    ["0xc6", "0xc7"],
    "fp_arith_scalar_single_128b_packed_double_512b_packed_single": [
        "0x86", "0xc7"
    ],
    "fp_arith_scalar_single_128b_packed_single": ["0x0a", "0xc7"],
    "fp_arith_scalar_single_128b_packed_single_256b_packed_double": [
        "0x1a", "0xc7"
    ],
    "fp_arith_scalar_single_128b_packed_single_256b_packed_double_256b_packed_single":
    ["0x3a", "0xc7"],
    "fp_arith_scalar_single_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_double":
    ["0x7a", "0xc7"],
    "fp_arith_scalar_single_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xfa", "0xc7"],
    "fp_arith_scalar_single_128b_packed_single_256b_packed_double_256b_packed_single_512b_packed_single":
    ["0xba", "0xc7"],
    "fp_arith_scalar_single_128b_packed_single_256b_packed_double_512b_packed_double":
    ["0x5a", "0xc7"],
    "fp_arith_scalar_single_128b_packed_single_256b_packed_double_512b_packed_double_512b_packed_single":
    ["0xda", "0xc7"],
    "fp_arith_scalar_single_128b_packed_single_256b_packed_double_512b_packed_single":
    ["0x9a", "0xc7"],
    "fp_arith_scalar_single_128b_packed_single_256b_packed_single": [
        "0x2a", "0xc7"
    ],
    "fp_arith_scalar_single_128b_packed_single_256b_packed_single_512b_packed_double":
    ["0x6a", "0xc7"],
    "fp_arith_scalar_single_128b_packed_single_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xea", "0xc7"],
    "fp_arith_scalar_single_128b_packed_single_256b_packed_single_512b_packed_single":
    ["0xaa", "0xc7"],
    "fp_arith_scalar_single_128b_packed_single_512b_packed_double": [
        "0x4a", "0xc7"
    ],
    "fp_arith_scalar_single_128b_packed_single_512b_packed_double_512b_packed_single":
    ["0xca", "0xc7"],
    "fp_arith_scalar_single_128b_packed_single_512b_packed_single": [
        "0x8a", "0xc7"
    ],
    "fp_arith_scalar_single_256b_packed_double": ["0x12", "0xc7"],
    "fp_arith_scalar_single_256b_packed_double_256b_packed_single": [
        "0x32", "0xc7"
    ],
    "fp_arith_scalar_single_256b_packed_double_256b_packed_single_512b_packed_double":
    ["0x72", "0xc7"],
    "fp_arith_scalar_single_256b_packed_double_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xf2", "0xc7"],
    "fp_arith_scalar_single_256b_packed_double_256b_packed_single_512b_packed_single":
    ["0xb2", "0xc7"],
    "fp_arith_scalar_single_256b_packed_double_512b_packed_double": [
        "0x52", "0xc7"
    ],
    "fp_arith_scalar_single_256b_packed_double_512b_packed_double_512b_packed_single":
    ["0xd2", "0xc7"],
    "fp_arith_scalar_single_256b_packed_double_512b_packed_single": [
        "0x92", "0xc7"
    ],
    "fp_arith_scalar_single_256b_packed_single": ["0x22", "0xc7"],
    "fp_arith_scalar_single_256b_packed_single_512b_packed_double": [
        "0x62", "0xc7"
    ],
    "fp_arith_scalar_single_256b_packed_single_512b_packed_double_512b_packed_single":
    ["0xe2", "0xc7"],
    "fp_arith_scalar_single_256b_packed_single_512b_packed_single": [
        "0xa2", "0xc7"
    ],
    "fp_arith_scalar_single_512b_packed_double": ["0x42", "0xc7"],
    "fp_arith_scalar_single_512b_packed_double_512b_packed_single": [
        "0xc2", "0xc7"
    ],
    "fp_arith_scalar_single_512b_packed_single": ["0x82", "0xc7"],
    "hle_retired_aborted": ["0x04", "0xc8"],
    "hle_retired_aborted_events": ["0x80", "0xc8"],
    "hle_retired_aborted_mem": ["0x08", "0xc8"],
    "hle_retired_aborted_memtype": ["0x40", "0xc8"],
    "hle_retired_aborted_tmr": ["0x10", "0xc8"],
    "hle_retired_aborted_unfriendly": ["0x20", "0xc8"],
    "hle_retired_commit": ["0x02", "0xc8"],
    "hle_retired_start": ["0x01", "0xc8"],
    "hw_interrupts_received": ["0x01", "0xcb"],
    "icache_16b_ifdata_stall": ["0x04", "0x80"],
    "icache_64b_iftag_hit": ["0x01", "0x83"],
    "icache_64b_iftag_miss": ["0x02", "0x83"],
    "icache_64b_iftag_stall": ["0x04", "0x83"],
    "idq_all_mite_uops": ["0x3c", "0x79"],
    "idq_dsb_uops": ["0x08", "0x79"],
    "idq_mite_uops": ["0x04", "0x79"],
    "idq_ms_dsb_uops": ["0x10", "0x79"],
    "idq_ms_mite_uops": ["0x20", "0x79"],
    "idq_ms_uops": ["0x30", "0x79"],
    "idq_uops_not_delivered_core": ["0x01", "0x9c"],
    "ild_stall_lcp": ["0x01", "0x87"],
    "inst_retired_all": ["0x01", "0xc0"],
    "inst_retired_any_p": ["0x00", "0xc0"],
    "int_misc_clear_resteer_cycles": ["0x80", "0x0d"],
    "int_misc_recovery_cycles": ["0x01", "0x0d"],
    "itlb_itlb_flush": ["0x01", "0xae"],
    "itlb_misses_miss_causes_a_walk": ["0x01", "0x85"],
    "itlb_misses_stlb_hit": ["0x20", "0x85"],
    "itlb_misses_walk_completed": ["0x0e", "0x85"],
    "itlb_misses_walk_completed_1g": ["0x08", "0x85"],
    "itlb_misses_walk_completed_2m_4m": ["0x04", "0x85"],
    "itlb_misses_walk_completed_4k": ["0x02", "0x85"],
    "itlb_misses_walk_pending": ["0x10", "0x85"],
    "l1d_pend_miss_fb_full": ["0x02", "0x48"],
    "l1d_pend_miss_pending": ["0x01", "0x48"],
    "l1d_replacement": ["0x01", "0x51"],
    "l2_lines_in_any": ["0x1f", "0xf1"],
    "l2_lines_out_non_silent": ["0x02", "0xf2"],
    "l2_lines_out_silent": ["0x01", "0xf2"],
    "l2_lines_out_useless_hwpf": ["0x04", "0xf2"],
    "l2_rqsts_all_code_rd": ["0xe4", "0x24"],
    "l2_rqsts_all_demand_data_rd": ["0xe1", "0x24"],
    "l2_rqsts_all_demand_miss": ["0x27", "0x24"],
    "l2_rqsts_all_demand_references": ["0xe7", "0x24"],
    "l2_rqsts_all_pf": ["0xf8", "0x24"],
    "l2_rqsts_all_rfo": ["0xe2", "0x24"],
    "l2_rqsts_code_rd_hit": ["0xc4", "0x24"],
    "l2_rqsts_code_rd_miss": ["0x24", "0x24"],
    "l2_rqsts_demand_data_rd_hit": ["0xc1", "0x24"],
    "l2_rqsts_demand_data_rd_miss": ["0x21", "0x24"],
    "l2_rqsts_miss": ["0x3f", "0x24"],
    "l2_rqsts_pf_hit": ["0xd8", "0x24"],
    "l2_rqsts_pf_miss": ["0x38", "0x24"],
    "l2_rqsts_references": ["0xff", "0x24"],
    "l2_rqsts_rfo_hit": ["0xc2", "0x24"],
    "l2_rqsts_rfo_miss": ["0x22", "0x24"],
    "l2_trans_l2_wb": ["0x40", "0xf0"],
    "ld_blocks_no_sr": ["0x08", "0x03"],
    "ld_blocks_partial_address_alias": ["0x01", "0x07"],
    "ld_blocks_store_forward": ["0x02", "0x03"],
    "store_forward": ["0x02", "0x03"],
    "llc_misses": ["0x41", "0x2e"],
    "llc_references": ["0x4f", "0x2e"],
    "load_hit_pre_sw_pf": ["0x01", "0x4c"],
    "lock_cycles_cache_lock_duration": ["0x02", "0x63"],
    "lsd_uops": ["0x01", "0xa8"],
    "machine_clears_memory_ordering": ["0x02", "0xc3"],
    "machine_clears_smc": ["0x04", "0xc3"],
    "mem_load_l3_hit_retired_xsnp_hit": ["0x02", "0xd2"],
    "mem_load_l3_hit_retired_xsnp_hitm": ["0x04", "0xd2"],
    "mem_load_l3_hit_retired_xsnp_miss": ["0x01", "0xd2"],
    "mem_load_l3_hit_retired_xsnp_none": ["0x08", "0xd2"],
    "mem_load_l3_miss_retired_local_dram": ["0x01", "0xd3"],
    "mem_load_misc_retired_uc": ["0x04", "0xd4"],
    "mem_load_retired_fb_hit": ["0x40", "0xd1"],
    "mem_load_retired_l1_hit": ["0x01", "0xd1"],
    "l1_hit": ["0x01", "0xd1"],
    "l1_miss": ["0x08", "0xd1"],
    "mem_load_retired_l1_miss": ["0x08", "0xd1"],
    "mem_load_retired_l2_hit": ["0x02", "0xd1"],
    "mem_load_retired_l2_miss": ["0x10", "0xd1"],
    "mem_load_retired_l3_hit": ["0x04", "0xd1"],
    "mem_load_retired_l3_miss": ["0x20", "0xd1"],
    "mem_uops_retired_all_loads": ["0x81", "0xd0"],
    "mem_uops_retired_all_stores": ["0x82", "0xd0"],
    "mem_uops_retired_lock_loads": ["0x21", "0xd0"],
    "mem_uops_retired_split_loads": ["0x41", "0xd0"],
    "mem_uops_retired_split_stores": ["0x42", "0xd0"],
    "mem_uops_retired_stlb_miss_loads": ["0x11", "0xd0"],
    "mem_uops_retired_stlb_miss_stores": ["0x12", "0xd0"],
    "misalign_mem_ref_loads": ["0x01", "0x05"],
    "misalign_mem_ref_stores": ["0x02", "0x05"],
    "mispredicted_branch_retired": ["0x00", "0xc5"],
    "move_elimination_int_eliminated": ["0x01", "0x58"],
    "move_elimination_int_not_eliminated": ["0x04", "0x58"],
    "move_elimination_simd_eliminated": ["0x02", "0x58"],
    "move_elimination_simd_not_eliminated": ["0x08", "0x58"],
    "offcore_requests_all_data_rd": ["0x08", "0xb0"],
    "offcore_requests_all_requests": ["0x80", "0xb0"],
    "offcore_requests_buffer_sq_full": ["0x01", "0xb2"],
    "offcore_requests_demand_code_rd": ["0x02", "0xb0"],
    "offcore_requests_demand_data_rd": ["0x01", "0xb0"],
    "offcore_requests_demand_rfo": ["0x04", "0xb0"],
    "offcore_requests_l3_miss_demand_data_rd": ["0x10", "0xb0"],
    "offcore_requests_outstanding_all_data_rd": ["0x08", "0x60"],
    "offcore_requests_outstanding_demand_code_rd": ["0x02", "0x60"],
    "offcore_requests_outstanding_demand_data_rd": ["0x01", "0x60"],
    "offcore_requests_outstanding_demand_rfo": ["0x04", "0x60"],
    "offcore_requests_outstanding_l3_miss_demand_data_rd": ["0x10", "0x60"],
    "other_assists_any": ["0x3f", "0xc1"],
    "partial_rat_stalls_scoreboard": ["0x01", "0x59"],
    "resource_stalls_all": ["0x01", "0xa2"],
    "resource_stalls_rob": ["0x10", "0xa2"],
    "resource_stalls_rs": ["0x04", "0xa2"],
    "resource_stalls_sb": ["0x08", "0xa2"],
    "rob_misc_events_lbr_inserts": ["0x20", "0xcc"],
    "rob_misc_events_pause_inst": ["0x40", "0xcc"],
    "rs_events_empty_cycles": ["0x01", "0x5e"],
    "rtm_retired_aborted": ["0x04", "0xc9"],
    "rtm_retired_aborted_events": ["0x80", "0xc9"],
    "rtm_retired_aborted_mem": ["0x08", "0xc9"],
    "rtm_retired_aborted_memtype": ["0x40", "0xc9"],
    "rtm_retired_aborted_tmr": ["0x10", "0xc9"],
    "rtm_retired_aborted_unfriendly": ["0x20", "0xc9"],
    "rtm_retired_commit": ["0x02", "0xc9"],
    "rtm_retired_start": ["0x01", "0xc9"],
    "sq_misc_split_lock": ["0x10", "0xf4"],
    "sw_prefetch_nta": ["0x01", "0x32"],
    "sw_prefetch_prefetchw": ["0x08", "0x32"],
    "sw_prefetch_t0": ["0x02", "0x32"],
    "sw_prefetch_t1_t2": ["0x04", "0x32"],
    "tlb_flush_dtlb_thread": ["0x01", "0xbd"],
    "tlb_flush_stlb_any": ["0x20", "0xbd"],
    "tx_exec_misc1": ["0x01", "0x5d"],
    "tx_exec_misc2": ["0x02", "0x5d"],
    "tx_exec_misc3": ["0x04", "0x5d"],
    "tx_exec_misc4": ["0x08", "0x5d"],
    "tx_exec_misc5": ["0x10", "0x5d"],
    "tx_mem_abort_capacity": ["0x02", "0x54"],
    "tx_mem_abort_conflict": ["0x01", "0x54"],
    "tx_mem_abort_hle_elision_buffer_full": ["0x40", "0x54"],
    "tx_mem_abort_hle_elision_buffer_mismatch": ["0x10", "0x54"],
    "tx_mem_abort_hle_elision_buffer_not_empty": ["0x08", "0x54"],
    "tx_mem_abort_hle_elision_buffer_unsupported_alignment": ["0x20", "0x54"],
    "tx_mem_abort_hle_store_to_elided_lock": ["0x04", "0x54"],
    "unhalted_reference_cycles": ["0x01", "0x3c"],
    "unhalted_reference_cycles_ref_xclk": ["0x03", "0x00"],
    "uops_dispatched_port_0": ["0x01", "0xa1"],
    "uops_dispatched_port_1": ["0x02", "0xa1"],
    "uops_dispatched_port_2": ["0x04", "0xa1"],
    "uops_dispatched_port_3": ["0x08", "0xa1"],
    "uops_dispatched_port_4": ["0x10", "0xa1"],
    "uops_dispatched_port_5": ["0x20", "0xa1"],
    "uops_dispatched_port_6": ["0x40", "0xa1"],
    "uops_dispatched_port_7": ["0x80", "0xa1"],
    "uops_executed_core": ["0x02", "0xb1"],
    "uops_executed_thread": ["0x01", "0xb1"],
    "uops_executed_x87": ["0x10", "0xb1"],
    "uops_issued_all": ["0x01", "0x0e"],
    "uops_issued_flags_merge": ["0x10", "0x0e"],
    "uops_issued_single_mul": ["0x40", "0x0e"],
    "uops_issued_slow_lea": ["0x20", "0x0e"],
    "uops_issued_vector_width_mismatch": ["0x02", "0x0e"],
    "uops_retired_any": ["0x01", "0xc2"],
    "uops_retired_retire_slots": ["0x02", "0xc2"]
}

icl_events = {
    "assists_any": ["0x07", "0xc1"],
    "assists_fp": ["0x02", "0xc1"],
    "baclears_any": ["0x01", "0xe6"],
    "baclears": ["0x01", "0xe6"],
    "branch_instructions_retired": ["0x00", "0xc4"],
    "br_inst_retired_cond": ["0x11", "0xc4"],
    "br_inst_retired_cond_ntaken": ["0x10", "0xc4"],
    "br_inst_retired_cond_taken": ["0x01", "0xc4"],
    "br_inst_retired_far_branch": ["0x40", "0xc4"],
    "br_inst_retired_indirect": ["0x80", "0xc4"],
    "br_inst_retired_near_call": ["0x02", "0xc4"],
    "br_inst_retired_near_return": ["0x08", "0xc4"],
    "br_inst_retired_near_taken": ["0x20", "0xc4"],
    "br_misp_retired_cond": ["0x11", "0xc5"],
    "br_misp_retired_cond_ntaken": ["0x10", "0xc5"],
    "br_misp_retired_cond_taken": ["0x01", "0xc5"],
    "br_misp_retired_indirect": ["0x80", "0xc5"],
    "br_misp_retired_indirect_call": ["0x02", "0xc5"],
    "br_misp_retired_near_taken": ["0x20", "0xc5"],
    "core_power_lvl0_turbo_license": ["0x07", "0x28"],
    "core_power_lvl1_turbo_license": ["0x18", "0x28"],
    "core_power_lvl2_turbo_license": ["0x20", "0x28"],
    "cpu_clk_unhalted_distributed": ["0x02", "0xec"],
    "cpu_clk_unhalted_one_thread_active": ["0x02", "0x3c"],
    "cpu_clk_unhalted_ref_distributed": ["0x08", "0xec"],
    "cpu_clk_unhalted_ref_tsc": ["0x03", "0x3c"],
    "cpu_clk_unhalted_ref_xclk": ["0x01", "0x3c"],
    "dsb2mite_switches_penalty_cycles": ["0x02", "0xab"],
    "dsb2mite_cycles": ["0x02", "0xab"],
    "dtlb_load_misses_stlb_hit": ["0x20", "0x08"],
    "dtlb_load_misses_walk_completed": ["0x0e", "0x08"],
    "dtlb_load_misses_walk_completed_2m_4m": ["0x04", "0x08"],
    "dtlb_load_misses_walk_completed_4k": ["0x02", "0x08"],
    "dtlb_load_misses_walk_pending": ["0x10", "0x08"],
    "dtlb_store_misses_stlb_hit": ["0x20", "0x49"],
    "dtlb_store_misses_walk_completed": ["0x0e", "0x49"],
    "dtlb_store_misses_walk_completed_2m_4m": ["0x04", "0x49"],
    "dtlb_store_misses_walk_completed_4k": ["0x02", "0x49"],
    "dtlb_store_misses_walk_pending": ["0x10", "0x49"],
    "exe_activity_1_ports_util": ["0x02", "0xa6"],
    "exe_activity_2_ports_util": ["0x04", "0xa6"],
    "exe_activity_3_ports_util": ["0x08", "0xa6"],
    "exe_activity_4_ports_util": ["0x10", "0xa6"],
    "exe_activity_exe_bound_0_ports": ["0x80", "0xa6"],
    "fp_arith_128b_packed_double": ["0x04", "0xc7"],
    "fp_arith_128b_packed_single": ["0x08", "0xc7"],
    "fp_arith_256b_packed_double": ["0x10", "0xc7"],
    "fp_arith_256b_packed_single": ["0x20", "0xc7"],
    "fp_arith_512b_packed_double": ["0x40", "0xc7"],
    "fp_arith_512b_packed_single": ["0x80", "0xc7"],
    "fp_arith_scalar_double": ["0x01", "0xc7"],
    "fp_arith_scalar_single": ["0x02", "0xc7"],
    "hle_retired_aborted": ["0x04", "0xc8"],
    "hle_retired_aborted_events": ["0x80", "0xc8"],
    "hle_retired_aborted_mem": ["0x08", "0xc8"],
    "hle_retired_aborted_unfriendly": ["0x20", "0xc8"],
    "hle_retired_commit": ["0x02", "0xc8"],
    "hle_retired_start": ["0x01", "0xc8"],
    "icache_16b_ifdata_stall": ["0x04", "0x80"],
    "icache_64b_iftag_hit": ["0x01", "0x83"],
    "icache_64b_iftag_miss": ["0x02", "0x83"],
    "icache_64b_iftag_stall": ["0x04", "0x83"],
    "idq_dsb_uops": ["0x08", "0x79"],
    "idq_mite_uops": ["0x04", "0x79"],
    "idq_ms_uops": ["0x30", "0x79"],
    "dsb_uops": ["0x08", "0x79"],
    "mite_uops": ["0x04", "0x79"],
    "ms_uops": ["0x30", "0x79"],
    "idq_uops_not_delivered_core": ["0x01", "0x9c"],
    "idq_ndelivered": ["0x01", "0x9c"],
    "idq_nd": ["0x01", "0x9c"],
    "ild_stall_lcp": ["0x01", "0x87"],
    "inst_retired_any_p": ["0x00", "0xc0"],
    "int_misc_clear_resteer_cycles": ["0x80", "0x0d"],
    "int_misc_recovery_cycles": ["0x01", "0x0d"],
    "int_misc_uop_dropping": ["0x10", "0x0d"],
    "itlb_misses_stlb_hit": ["0x20", "0x85"],
    "itlb_misses_walk_completed": ["0x0e", "0x85"],
    "itlb_misses_walk_completed_2m_4m": ["0x04", "0x85"],
    "itlb_misses_walk_completed_4k": ["0x02", "0x85"],
    "itlb_misses_walk_pending": ["0x10", "0x85"],
    "l1d_pend_miss_fb_full": ["0x02", "0x48"],
    "l1d_pend_miss_l2_stall": ["0x04", "0x48"],
    "l1d_pend_miss_pending": ["0x01", "0x48"],
    "l1d_replacement": ["0x01", "0x51"],
    "l2_lines_in_all": ["0x1f", "0xf1"],
    "l2_lines_out_non_silent": ["0x02", "0xf2"],
    "l2_lines_out_silent": ["0x01", "0xf2"],
    "l2_lines_out_useless_hwpf": ["0x04", "0xf2"],
    "l2_rqsts_all_code_rd": ["0xe4", "0x24"],
    "l2_rqsts_all_demand_data_rd": ["0xe1", "0x24"],
    "l2_rqsts_all_demand_miss": ["0x27", "0x24"],
    "l2_rqsts_all_demand_references": ["0xe7", "0x24"],
    "l2_rqsts_all_rfo": ["0xe2", "0x24"],
    "l2_rqsts_code_rd_hit": ["0xc4", "0x24"],
    "l2_rqsts_code_rd_miss": ["0x24", "0x24"],
    "l2_rqsts_demand_data_rd_hit": ["0xc1", "0x24"],
    "l2_rqsts_demand_data_rd_miss": ["0x21", "0x24"],
    "l2_rqsts_rfo_hit": ["0xc2", "0x24"],
    "l2_rqsts_rfo_miss": ["0x22", "0x24"],
    "l2_rqsts_swpf_hit": ["0xc8", "0x24"],
    "l2_rqsts_swpf_miss": ["0x28", "0x24"],
    "l2_trans_l2_wb": ["0x40", "0xf0"],
    "ld_blocks_no_sr": ["0x08", "0x03"],
    "ld_blocks_partial_address_alias": ["0x01", "0x07"],
    "ld_blocks_store_forward": ["0x02", "0x03"],
    "llc_misses": ["0x41", "0x2e"],
    "llc_references": ["0x4f", "0x2e"],
    "load_hit_pre_swpf": ["0x01", "0x4c"],
    "longest_lat_cache_miss": ["0x01", "0x2e"],
    "lsd_uops": ["0x01", "0xa8"],
    "machine_clears_memory_ordering": ["0x02", "0xc3"],
    "machine_clears_smc": ["0x04", "0xc3"],
    "mem_inst_retired_all_loads": ["0x81", "0xd0"],
    "mem_inst_retired_all_stores": ["0x82", "0xd0"],
    "mem_inst_retired_lock_loads": ["0x21", "0xd0"],
    "mem_inst_retired_split_loads": ["0x41", "0xd0"],
    "mem_inst_retired_split_stores": ["0x42", "0xd0"],
    "mem_inst_retired_stlb_miss_loads": ["0x11", "0xd0"],
    "mem_inst_retired_stlb_miss_stores": ["0x12", "0xd0"],
    "mem_load_l3_hit_retired_xsnp_hit": ["0x02", "0xd2"],
    "mem_load_l3_hit_retired_xsnp_hitm": ["0x04", "0xd2"],
    "mem_load_l3_hit_retired_xsnp_miss": ["0x01", "0xd2"],
    "mem_load_l3_hit_retired_xsnp_none": ["0x08", "0xd2"],
    "mem_load_retired_fb_hit": ["0x40", "0xd1"],
    "l1_hit": ["0x01", "0xd1"],
    "l1_miss": ["0x08", "0xd1"],
    "mem_load_retired_l1_hit": ["0x01", "0xd1"],
    "mem_load_retired_l1_miss": ["0x08", "0xd1"],
    "mem_load_retired_l2_hit": ["0x02", "0xd1"],
    "mem_load_retired_l2_miss": ["0x10", "0xd1"],
    "mem_load_retired_l3_hit": ["0x04", "0xd1"],
    "mem_load_retired_l3_miss": ["0x20", "0xd1"],
    "misc_retired_lbr_inserts": ["0x20", "0xcc"],
    "misc_retired_pause_inst": ["0x40", "0xcc"],
    "mispredicted_branch_retired": ["0x00", "0xc5"],
    "br_misp": ["0x00", "0xc5"],
    "branch_misp": ["0x00", "0xc5"],
    "branch_misses": ["0x00", "0xc5"],
    "branch-misses": ["0x00", "0xc5"],
    "offcore_requests_all_data_rd": ["0x08", "0xb0"],
    "offcore_requests_all_requests": ["0x80", "0xb0"],
    "offcore_requests_demand_data_rd": ["0x01", "0xb0"],
    "offcore_requests_demand_rfo": ["0x04", "0xb0"],
    "offcore_requests_l3_miss_demand_data_rd": ["0x10", "0xb0"],
    "offcore_requests_outstanding_all_data_rd": ["0x08", "0x60"],
    "offcore_requests_outstanding_demand_data_rd": ["0x01", "0x60"],
    "offcore_requests_outstanding_demand_rfo": ["0x04", "0x60"],
    "resource_stalls_sb": ["0x08", "0xa2"],
    "resource_stalls_scoreboard": ["0x02", "0xa2"],
    "rs_events_empty_cycles": ["0x01", "0x5e"],
    "rtm_retired_aborted": ["0x04", "0xc9"],
    "rtm_retired_aborted_events": ["0x80", "0xc9"],
    "rtm_retired_aborted_mem": ["0x08", "0xc9"],
    "rtm_retired_aborted_memtype": ["0x40", "0xc9"],
    "rtm_retired_aborted_unfriendly": ["0x20", "0xc9"],
    "rtm_retired_commit": ["0x02", "0xc9"],
    "rtm_retired_start": ["0x01", "0xc9"],
    "sq_misc_sq_full": ["0x04", "0xf4"],
    "sw_prefetch_nta": ["0x01", "0x32"],
    "sw_prefetch_prefetchw": ["0x08", "0x32"],
    "sw_prefetch_t0": ["0x02", "0x32"],
    "sw_prefetch_t1_t2": ["0x04", "0x32"],
    "tlb_flush_dtlb_thread": ["0x01", "0xbd"],
    "tlb_flush_stlb_any": ["0x20", "0xbd"],
    "topdown_backend_bound_slots": ["0x02", "0x00"],
    "topdown_br_mispredict_slots": ["0x08", "0x00"],
    "topdown_slots": ["0x04", "0x00"],
    "topdown_slots_p": ["0x01", "0x00"],
    "tx_exec_misc2": ["0x02", "0x5d"],
    "tx_exec_misc3": ["0x04", "0x5d"],
    "tx_mem_abort_capacity_read": ["0x80", "0x54"],
    "tx_mem_abort_capacity_write": ["0x02", "0x54"],
    "tx_mem_abort_conflict": ["0x01", "0x54"],
    "tx_mem_abort_hle_elision_buffer_mismatch": ["0x10", "0x54"],
    "tx_mem_abort_hle_elision_buffer_not_empty": ["0x08", "0x54"],
    "tx_mem_abort_hle_elision_buffer_unsupported_alignment": ["0x20", "0x54"],
    "tx_mem_abort_hle_store_to_elided_lock": ["0x04", "0x54"],
    "tx_mem_hle_elision_buffer_full": ["0x40", "0x54"],
    "unhalted_core_cycles": ["0x00", "0x3c"],
    "unhalted_reference_cycles": ["0x03", "0x00"],
    "uops_dispatched_port_0": ["0x01", "0xa1"],
    "uops_dispatched_port_1": ["0x02", "0xa1"],
    "uops_dispatched_port_2_3": ["0x04", "0xa1"],
    "uops_dispatched_port_4_9": ["0x10", "0xa1"],
    "uops_dispatched_port_5": ["0x20", "0xa1"],
    "uops_dispatched_port_6": ["0x40", "0xa1"],
    "uops_dispatched_port_7_8": ["0x80", "0xa1"],
    "port_0": ["0x01", "0xa1"],
    "port_1": ["0x02", "0xa1"],
    "port_2_3": ["0x04", "0xa1"],
    "port_4_9": ["0x10", "0xa1"],
    "port_5": ["0x20", "0xa1"],
    "port_6": ["0x40", "0xa1"],
    "port_7_8": ["0x80", "0xa1"],
    "p0": ["0x01", "0xa1"],
    "p1": ["0x02", "0xa1"],
    "p23": ["0x04", "0xa1"],
    "p49": ["0x10", "0xa1"],
    "p5": ["0x20", "0xa1"],
    "p6": ["0x40", "0xa1"],
    "p78": ["0x80", "0xa1"],
    "uops_executed_core": ["0x02", "0xb1"],
    "uops_executed_thread": ["0x01", "0xb1"],
    "uops_executed_x87": ["0x10", "0xb1"],
    "uops_issued_any": ["0x01", "0x0e"],
    "uops_retired_slots": ["0x02", "0xc2"],
    "uops_issued": ["0x01", "0x0e"],
    "uops_retired": ["0x02", "0xc2"],
    "cycles": None,
    "cpu-cycles": None,
    "ref-cycles": None,
    "instructions": None,
    "context-switches": None,
    "cs": None,
}

perf_cmd_fmt = "perf stat {} --all-user -e {} {} {}"
event_fmt = "cpu/event={},umask={},name={}/"

parser = argparse.ArgumentParser(description="Wrapper for perf stat")
parser.add_argument("-e",
                    action="store",
                    default=None,
                    help="CSV of event names")

parser.add_argument("--dump",
                    action="store_true",
                    default=False,
                    help="Dump event")

parser.add_argument("-x",
                    action="store_true",
                    default=False,
                    help="Output as csv")

parser.add_argument("-l",
                    "--lib",
                    action="store",
                    default=None,
                    help="PRELOAD argument before running")


class Event():
    def __init__(self, ev_name, event_dict):
        ev_name = ev_name.lower()
        assert ev_name in event_dict, "Cant find: \"{}\"".format(ev_name)
        global umask_idx
        global event_idx

        ev_info = event_dict[ev_name]

        self.name = ev_name
        self.umask = None
        self.ev = None

        if ev_info is not None:
            self.umask = ev_info[umask_idx]
            self.ev = ev_info[event_idx]

    def ev_fmt_out(self):
        global event_fmt
        if self.umask is None:
            return self.name
        return event_fmt.format(self.ev, self.umask, self.name)

    def dump_fmt_out(self):
        return "[{0:60}, {1:4}, {2:4}]".format(self.name, str(self.umask),
                                               str(self.ev))

    def fmt_out(self, dump):
        if dump:
            return self.dump_fmt_out()
        return self.ev_fmt_out()


def delim_out(elements, delim):
    out = ""
    for ele in elements:
        if out != "":
            out += delim
        out += ele
    return out


def csv_out(elements):
    return delim_out(elements, ",")


def eve_out(elements):
    return delim_out(elements, " ")


def perf_env(ld_lib):
    if lib is None:
        return ""

    return "env LD_PRELOAD=./{}".format(ld_lib)


args, unknownargs = parser.parse_known_args()
events = args.e
dump = args.dump
lib = args.lib
xarg = args.x

assert events is not None or dump

ev_list = []
if events is None:
    assert dump
    for ev_key in icl_events:
        ev = Event(ev_key, icl_events)
        ev_list.append(ev.dump_fmt_out())
    for ev in ev_list:
        print(ev)
else:
    events = events.split(",")
    for ev_key in events:
        ev = Event(ev_key, icl_events)
        ev_list.append(ev.ev_fmt_out())
    exe = eve_out(unknownargs)
    ev_csv = csv_out(ev_list)
    env = perf_env(lib)

    perf_as_csv = ""
    if xarg:
        perf_as_csv = "-x,"

    if dump:
        print(perf_cmd_fmt.format(perf_as_csv, ev_csv, env, exe))
    else:
        os.system(perf_cmd_fmt.format(perf_as_csv, ev_csv, env, exe))
